const res = {
  allowsExternalPlayback: true,
  audioMixingMode: 'doNotMix',
  availableSubtitleTracks: [],
  bufferOptions: { preferredForwardBufferDuration: 0, waitsToMinimizeStalling: true },
  bufferedPosition: 0,
  currentLiveTimestamp: null,
  currentOffsetFromLive: null,
  currentTime: 0,
  duration: 0,
  isLive: true,
  loop: false,
  muted: false,
  playbackRate: 1,
  playing: false,
  preservesPitch: true,
  showNowPlayingNotification: false,
  status: 'loading',
  staysActiveInBackground: false,
  subtitleTrack: null,
  targetOffsetFromLive: NaN,
  timeUpdateEventInterval: 0,
  volume: 1,
};
